=== rajat806/Csci-226-XML-DTD-Discussion-/domain.dtd
<!ELEMENT cvs (refill)>
<!ELEMENT refill (rx, copay, stock, method, eta?, coupon?)>
<!ATTLIST refill id ID #REQUIRED date CDATA #REQUIRED>

<!ELEMENT rx (drug, dosage, due)>
<!ELEMENT drug (#PCDATA)>
<!ELEMENT dosage (#PCDATA)>
<!ELEMENT due (#PCDATA)>

<!ELEMENT copay (#PCDATA)>

<!ELEMENT stock EMPTY>
<!ATTLIST stock status (in_stock|out_of_stock) #REQUIRED>

<!ELEMENT method EMPTY>
<!ATTLIST method type (pickup|delivery) #REQUIRED>

<!ELEMENT eta (#PCDATA)>       <!-- minutes or time window -->
<!ELEMENT coupon (#PCDATA)>    <!-- code like SAVE10 -->

=== rajat806/Csci-226-XML-DTD-Discussion-/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE cvs SYSTEM "domain.dtd">
<cvs>
  <refill id="r1" date="2025-09-02">
    <rx>
      <drug>Lisinopril</drug>
      <dosage>10mg</dosage>
      <due>2025-09-05</due>
    </rx>
    <copay>12.00</copay>
    <stock status="in_stock"/>
    <method type="pickup"/>
    <eta>30</eta>
    <coupon>EXTRACARE10</coupon>
  </refill>
</cvs>
